// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(BigSoftContext))]
    partial class BigSoftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Civility")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Identifiant_fiscale")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumMobile")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Telephone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Utilisateur");
                });

            modelBuilder.Entity("Data.Entities.Client", b =>
                {
                    b.HasBaseType("Data.Entities.Utilisateur");

                    b.Property<string>("Cin")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("TypeClient")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Data.Entities.Fournisseur", b =>
                {
                    b.HasBaseType("Data.Entities.Utilisateur");

                    b.Property<string>("CodePostale")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Fournisseur_CodePostale");

                    b.Property<int>("Numbureau")
                        .HasColumnType("int")
                        .HasColumnName("Fournisseur_Numbureau");

                    b.Property<string>("PersAContact")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fournisseur_PersAContact");

                    b.Property<string>("Rib")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Fournisseur_Rib");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fournisseur_SiteWeb");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit")
                        .HasColumnName("Fournisseur_Verified");

                    b.HasDiscriminator().HasValue("Fournisseur");
                });

            modelBuilder.Entity("Data.Entities.Grossiste", b =>
                {
                    b.HasBaseType("Data.Entities.Utilisateur");

                    b.Property<string>("CodePostale")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Numbureau")
                        .HasColumnType("int");

                    b.Property<string>("PersAContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rib")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Grossiste");
                });
#pragma warning restore 612, 618
        }
    }
}
